---
- hosts: db
  vars_files:
    - secrets.yml
  tasks:

    - name: Copy MariaDB
      become: yes
      copy: src=db/MariaDB.repo dest=/etc/yum.repos.d/MariaDB.repo mode=0644

    - name: Install MariaDB Client
      become: yes
      package: name-MariaDB-client update_cache=yes state=present 

    - name: Unzip Database
      become: yes
      unarchive: src=db/db.tgz dest=~/ mode=0777

    - name: Create Database
      become: yes
      command: ./make_databases.sh "{{ db_password }}" tf-lb-2016121503573704209403862c-271153429.us-west-2.elb.amazonaws.com chdir=~/db
      ignore_errors: True
