---
- hosts: web
  vars:
    server_name: curriculum
    service_name: curriculum
    service_version: 1.0
    app_env: test
    db_host: tf-lb-2016121503573704209403862c-271153429.us-west-2.elb.amazonaws.com
    db_database: curriculum
    db_username: csantos
    db_port: 3306
    service_dir: /usr/share/nginx/{{ service_name }}
  vars_files:
    - secrets.yml
  tasks:
    - name: Install epel-release
      become: yes
      yum: name=epel-release update_cache=yes state=present

    - name: Install nginx/php packages
      become: yes
      yum: name=nginx,php,php-fpm,php-ldap,php-mbstring,php-mcrypt,php-mysql,php-phpunit-PHPUnit update_cache=yes state=present
      register: nginx_install

    - name: Download composer
      become: yes
      shell: get_url -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer

    - name: Copy nginx config files
      become: yes
      copy: src=web/nginx.conf dest=/etc/nginx/nginx.conf mode=0644
      register: nginx_conf

    - name: Configure vhost
      become: yes
      template: src=web/vhost.conf.j2 dest=/etc/nginx/conf.d/{{ service_name }}.conf mode=0644
      register: vhost_conf

    - name: Configure php.ini file
      become: true
      template: src=web/php.ini.j2 dest=/etc/php.ini mode=0644
      register: php_conf

    - name: Copy php config file
      become: yes
      copy: src=web/php-fpm-web.conf dest=/etc/php-fpm.d/www.conf mode=0644
      register: php_fpm_conf

    - name: Restart nginx
      become: yes
      service: name=nginx state=restarted enabled=yes
      when: nginx_install|changed or nginx_conf|changed or vhost_conf|changed

    - name: Restart php-fpm
      become: yes
      service: name=php-fpm state=restarted enabled=yes
      when: nginx_install|changed or php_conf|changed or php_fpm_conf|changed

    - name: Create directory 
      become: yes
      file: path="{{ service_dir }}" state=directory

    - name: Unzip file
      become: yes
      unarchive: src=web/{{ service_name }}.tgz dest= "{{ service_dir }}" mode=0755

    - name: Update dirrectory
      become: yes
      command: /usr/local/bin/composer update chdir={{ service_dir }}

    - name: Change permissions
      become: yes
      file: chdir="{{ service_dir }}" mode 0777

    - name: Recurse path
      become: yes
      file: path="{{ service_dir }}" owner=nginx state=directory recurse=yes

    - name: Run template
      become: yes
      template: src=web/env.j2 dest="{{ service_dir }}/.env" mode=0644 owner=nginx